name: Metanorma builds via Docker

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build document in the Metanorma container
        env:
          JAVA_OPTS: "java.awt.headless=true"
          METANORMA_DOCKER: true
        run: |
          make clean all publish
      - uses: actions/upload-artifact@master
        with:
          name: published
          path: published

mn-deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: published
    - name: deploy-to-gh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/ghactions-deploy-gh-pages.sh | bash"
