name: Build and deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6' ]
    steps:
      - uses: actions/checkout@master
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Setup snaps
        run: |
          sudo snap install jq
          sudo snap install yq
      - name: Update gems
        run: |
          gem update --system
      - name: Setup Metanorma
        run: |
          sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"
          nvm use mn-node 
      - name: Build document
        env:
          JAVA_OPTS: "java.awt.headless=true"
        run: |
          make clean all publish

  mn-deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - name: deploy-to-gh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/deploy-to-gh-pages.sh | bash"

